theme = "harbor"
baseURL = "https://yasuhito.github.io/"
title = "Notes"
paginate = 10
languageCode = "ja"
DefaultContentLanguage = "ja"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir = "docs"

[Author]
  name = "Yasuhito Takamiya"

[outputs]
  section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[params.logo]
  url = "icon.png" # static/images/icon.png
  width = 50
  height = 50
  alt = "Logo"
