baseURL = "https://yasuhito.github.io/"
languageCode = "ja"
title = "Yasuhito's Zettel"
theme = "cactus"
disableHugoGeneratorInject = true
enableRobotsTXT = true
publishDir = "docs"
canonifyurls = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

[params]
  mathjax = true
